### PR TITLE
Policies functions + cleanup

### PR DESCRIPTION
**Pull request by mprenditore**
Hello, I've added the 4 basic functions to manage policies and cleaned up the code for PEP8 and removed unused import and var (I've tested with those commented out with success so I think are really useless but I'll wait for your feedback).

Hope you enjoy it!

Stefano

### CODE REVIEW

**Comment by mprenditore** [comment]
How fast! thanks dude :)

**Comment by mprenditore** [comment]
@deslum are you going to upload the updated version on PyPI?

**Comment by deslum** [comment]
done. 1.0.4. Please check

**Comment by mprenditore** [comment]
Perfect, just updated. Thank you!

**Pull request merged**
